### ISSUE TITLE
Symlinks (Junctions) require Admin for linking to network drives.

### ISSUE THREAD

**Issue by Azza276** [Azza276/OGN_DCS_MOD_Sync#11]
The use of junctions was fixed in issue #4 and commit 8af4af8. Thanks Fidel. Now we need to decide if users will have to option to separate the DCS folder and the OGN Mods folder overs network drives or only allow local volumes.

If only local volumes, then need to catch when network drives are selected and tell the user not to (and switch back to default)

If network drives allowed, advise the user that they need to be admin, and to run the app as admin. Code needs to be able to differentiate so that if local volumes, selected it uses junctions, if network volume selected then Symlinks.

**Comment by Azza276** [comment]
So @fiddyschmitt , this is my preference. Assuming Junctions work on local volumes which it says it does and those local volumes mean any HDD on a users computer (any and all hard drives essentially), then I don't see the point in allowing the use of network volumes. They are potentially slow (for consumer grade network hardware) and is not something I would recommend any one does anyway. That preference is to just use junctions, don't worry about symbolic links and just not allow network drives.

What are your thoughts?

**Comment by fiddyschmitt** [comment]
Agree. Sounds good. We can always revisit if someone needs that feature

**Comment by Azza276** [comment]
All agreed. Close issue. No Action.
