### ISSUE TITLE
Add way to delete DCS_Mods and Links without manually doing it 

### ISSUE THREAD

**Issue by MacGynan** [Azza276/OGN_DCS_MOD_Sync#19]
Have a so called "Fix/Clean" button  that removes OGN_Mods folder and associated skins and links. May come in handy if you are updating the file and have an issue and need to do a clean install. Rather than manually going into the Saved Games/DCS folder.

Not a really big improvement but a just quality of life.

**Comment by Azza276** [comment]
Thanks Macca, Its a good point. Although we did test from Symbolic links to the Junctions and it updates just fine, it we do make other significant changes in the future, this could be looked at. therefore pushed to V1.0 as something to consider going forward.

**Comment by Azza276** [comment]
This has been Added to the App as of Version 0.6. Although I suspect it is a little too drastic and there may be a need to be able to select Liveries Links and Mod Files separately... will await further issue/requests if that is the case.
