### ISSUE TITLE
Repeating FTP Connection Problem

### ISSUE THREAD

**Issue by razeddd** [Azza276/OGN_DCS_MOD_Sync#22]
![error_msg](https://user-images.githubusercontent.com/49805419/56453933-abc69400-638c-11e9-86f8-4233c2f866e6.PNG)
![download](https://user-images.githubusercontent.com/49805419/56453934-ac5f2a80-638c-11e9-8b00-c871d08c6511.PNG)
![download2](https://user-images.githubusercontent.com/49805419/56453960-0f50c180-638d-11e9-95d1-cf19f5e3f1af.PNG)

Hello, I have downloaded all but 8 files on the mod sync app and cannot download the rest. It seems to attempt to download the file however I get the above error every time.

**Comment by Azza276** [comment]
Hi Razed,

Are you using the latest version?
https://github.com/Azza276/OGN_DCS_MOD_Sync/releases/tag/0.3-alpha-hotfix1

**Comment by razeddd** [comment]
Yes, I am using version 0.3.0.1

**Comment by Azza276** [comment]
The hotfix one?
Nevermind.
I'll talk directly to you tonight.

**Comment by Azza276** [comment]
Talked to Razed. 
Internet connection not the best.
Recommended reducing Download Thread Count to 1 (was 4)
Issue appears fixed.
